# Generated by Django 4.1.5 on 2023-01-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patients_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='address_number',
            field=models.IntegerField(),
        ),
    ]
