# Generated by Django 4.1.5 on 2023-01-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_rename_address_street_patients_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='dni',
            field=models.CharField(max_length=11),
        ),
    ]
