# Generated by Django 4.1.4 on 2023-01-10 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patients_dni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='address',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='name',
            new_name='nombre_y_apellido',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='first_time',
            new_name='primer_consulta',
        ),
    ]
