# Generated by Django 4.1.4 on 2023-01-12 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_rename_address_patients_direccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='direccion',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='primer_consulta',
            new_name='first_query',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='nombre_y_apellido',
            new_name='name',
        ),
    ]
