# Generated by Django 4.1.5 on 2023-01-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('num_query', models.IntegerField()),
                ('weight', models.FloatField()),
                ('felling', models.FloatField()),
                ('age', models.FloatField()),
                ('vaccines', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
    ]
