# Generated by Django 4.1.5 on 2023-01-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='dni',
            field=models.CharField(max_length=11),
        ),
    ]
