# Generated by Django 4.1.4 on 2023-01-10 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_alter_queries_dni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queries',
            old_name='age',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='queries',
            old_name='num_query',
            new_name='n_consulta',
        ),
        migrations.RenameField(
            model_name='queries',
            old_name='felling',
            new_name='peso',
        ),
        migrations.RenameField(
            model_name='queries',
            old_name='weight',
            new_name='talla',
        ),
        migrations.RenameField(
            model_name='queries',
            old_name='vaccines',
            new_name='vacunas',
        ),
    ]
