# Generated by Django 4.1.4 on 2023-01-12 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0003_rename_age_queries_edad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queries',
            old_name='edad',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='queries',
            old_name='peso',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='queries',
            old_name='n_consulta',
            new_name='n_query',
        ),
        migrations.RenameField(
            model_name='queries',
            old_name='vacunas',
            new_name='vaccines',
        ),
        migrations.RenameField(
            model_name='queries',
            old_name='talla',
            new_name='weight',
        ),
    ]
